[package]
name = "composition_routed_stake"
edition = "2024"
license = "Apache 2.0"
authors = ["Miso Labs, Inc. (build@miso.network)"]

[dependencies]
miso = { git = "https://github.com/misofm/protocol.git", rev = "ffa0e38b8ba4815d81de1076101ea37d2c71c623" }
hikida = { git = "https://github.com/unconfirmedlabs/hikida.git", rev = "4abe4c1ff482655693698fa6ab8a6e2b58f8c635" }
royalty_pool = { git = "https://github.com/misofm/royalty-pool.git", rev = "a5407e77237052d02f8d664cba405c692e7fdae5" }
routed_stake = { git = "https://github.com/misofm/routed-stake.git", rev = "36dbfa1edb6560fd93b82d32144f323bea5a11ce" }
vault = { git = "https://github.com/misofm/vault.git", rev = "6b55f9fe8d89f7a7974cb843b10b9827fe13ef0f", modes = ["test"] }
