[package]
name = "release_revenue_distributor"
edition = "2024"
license = "Apache 2.0"
authors = ["Miso Labs, Inc. (build@miso.network)"]

[dependencies]
miso = { git = "https://github.com/misofm/protocol.git", rev = "09f0dc699a112c37d8da8a765596cc1ed623fe79" }
hikida = { git = "https://github.com/unconfirmedlabs/hikida.git", rev = "4abe4c1ff482655693698fa6ab8a6e2b58f8c635" }
vault = { git = "https://github.com/misofm/vault.git", rev = "8a4d1c0edbc120efc642a682308662e2a0b7f407", modes = ["test"] }
