[package]
name = "composition_royalty_pool"
edition = "2024"
license = "Apache 2.0"
authors = ["Miso Labs, Inc. (build@miso.fm)"]

[dependencies]
musicos = { git = "https://github.com/misofm/musicos.git", rev = "0b3eb07c9cb1af29c877b66cddfdcc9ef32fc721" }
hikida = { git = "https://github.com/unconfirmedlabs/hikida.git", rev = "c91d6a0f536a5f1457b342a8838fc1d7ba09212e" }
royalty_pool = { git = "https://github.com/misofm/royalty-pool.git", rev = "51affdec8df069be03779901e5e8797713ad147d" }
vault = { git = "https://github.com/misofm/vault.git", rev = "b39cbba9688d19aa651032f25ca27951746d13f6", modes = ["test"] }
share = { git = "https://github.com/unconfirmedlabs/share.git", rev = "08e0856b4248f011a93b26892bdf39cad0e2560b" }
